//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortForestPark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public System.DateTime DataCreated { get; set; }
        public System.TimeSpan TimeOrder { get; set; }
        public int Client { get; set; }
        public string Service { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public int RentalTime { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
